import { User, Thread, Category, Post } from "@/types/forum";

export const mockUsers: User[] = [
  {
    id: "1",
    username: "john_doe",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    joinDate: "2024-01-15",
    postCount: 342,
  },
  {
    id: "2",
    username: "jane_smith",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    joinDate: "2024-02-20",
    postCount: 156,
  },
  {
    id: "3",
    username: "tech_guru",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tech",
    joinDate: "2023-11-05",
    postCount: 890,
  },
  {
    id: "4",
    username: "newbie_dev",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Newbie",
    joinDate: "2024-03-01",
    postCount: 23,
  },
];

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "General Discussion",
    description: "Talk about anything and everything",
    threadCount: 1234,
    icon: "💬",
  },
  {
    id: "2",
    name: "Technology",
    description: "Latest tech news, gadgets, and innovations",
    threadCount: 856,
    icon: "💻",
  },
  {
    id: "3",
    name: "Programming",
    description: "Code, debug, and discuss programming topics",
    threadCount: 2341,
    icon: "👨‍💻",
  },
  {
    id: "4",
    name: "Web Development",
    description: "HTML, CSS, JavaScript, and modern frameworks",
    threadCount: 1567,
    icon: "🌐",
  },
  {
    id: "5",
    name: "Gaming",
    description: "Discuss your favorite games and gaming news",
    threadCount: 678,
    icon: "🎮",
  },
  {
    id: "6",
    name: "Help & Support",
    description: "Get help with technical issues",
    threadCount: 432,
    icon: "❓",
  },
];

export const mockPosts: Post[] = [
  {
    id: "p1",
    author: mockUsers[0],
    content: "I've been working with Next.js 14 and the new App Router is amazing! The server components really make a difference in performance. Has anyone else tried migrating from Pages Router?",
    createdAt: "2024-03-15T10:30:00Z",
    likes: 24,
  },
  {
    id: "p2",
    author: mockUsers[1],
    content: "Yes! I migrated a medium-sized project last month. The learning curve was steep but totally worth it. The best part is the built-in loading states and error handling.",
    createdAt: "2024-03-15T11:15:00Z",
    likes: 12,
  },
  {
    id: "p3",
    author: mockUsers[2],
    content: "Pro tip: Make sure to understand the difference between server and client components before starting. It'll save you a lot of headaches. Also, the new metadata API is fantastic for SEO!",
    createdAt: "2024-03-15T14:20:00Z",
    likes: 31,
  },
  {
    id: "p4",
    author: mockUsers[3],
    content: "Thanks for the tips! I'm just starting with Next.js. Any recommended resources for learning the App Router?",
    createdAt: "2024-03-15T16:45:00Z",
    likes: 5,
  },
];

export const mockThreads: Thread[] = [
  {
    id: "1",
    title: "Next.js 14 App Router - Migration Experience",
    author: mockUsers[0],
    category: "Web Development",
    createdAt: "2024-03-15T10:30:00Z",
    lastActivity: "2024-03-15T16:45:00Z",
    posts: mockPosts,
    postCount: 4,
    views: 234,
    isPinned: true,
  },
  {
    id: "2",
    title: "Best practices for TypeScript in 2024",
    author: mockUsers[2],
    category: "Programming",
    createdAt: "2024-03-14T09:15:00Z",
    lastActivity: "2024-03-15T18:20:00Z",
    posts: [],
    postCount: 18,
    views: 567,
    isPinned: true,
  },
  {
    id: "3",
    title: "How to optimize React performance?",
    author: mockUsers[1],
    category: "Web Development",
    createdAt: "2024-03-13T14:30:00Z",
    lastActivity: "2024-03-15T12:10:00Z",
    posts: [],
    postCount: 12,
    views: 432,
  },
  {
    id: "4",
    title: "Tailwind CSS vs CSS Modules - Which one to choose?",
    author: mockUsers[3],
    category: "Web Development",
    createdAt: "2024-03-12T11:20:00Z",
    lastActivity: "2024-03-15T09:30:00Z",
    posts: [],
    postCount: 23,
    views: 789,
  },
  {
    id: "5",
    title: "Welcome to the forum!",
    author: mockUsers[2],
    category: "General Discussion",
    createdAt: "2024-03-10T08:00:00Z",
    lastActivity: "2024-03-15T20:15:00Z",
    posts: [],
    postCount: 45,
    views: 1234,
    isPinned: true,
  },
  {
    id: "6",
    title: "Building a REST API with Node.js",
    author: mockUsers[0],
    category: "Programming",
    createdAt: "2024-03-11T15:45:00Z",
    lastActivity: "2024-03-14T17:30:00Z",
    posts: [],
    postCount: 8,
    views: 321,
  },
  {
    id: "7",
    title: "Best indie games of 2024",
    author: mockUsers[1],
    category: "Gaming",
    createdAt: "2024-03-09T19:20:00Z",
    lastActivity: "2024-03-15T13:45:00Z",
    posts: [],
    postCount: 34,
    views: 892,
  },
  {
    id: "8",
    title: "Help: Git merge conflicts",
    author: mockUsers[3],
    category: "Help & Support",
    createdAt: "2024-03-15T07:30:00Z",
    lastActivity: "2024-03-15T08:15:00Z",
    posts: [],
    postCount: 3,
    views: 145,
  },
];
